import type { NextPage } from 'next'
import Head from 'next/head'
import { 
  Box, 
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper
} from "@mui/material";
import { RootState } from '../redux/store'
import { useSelector } from 'react-redux'
import { PingPongModal } from "../components/pingpong/PingPongModal";

import * as React from "react"
import { API } from 'aws-amplify'
import {usePinPong} from "../components/hooks/usePingPong"
import {listPlayersByRank } from '../src/graphql/queries'
import { RankStat } from '../redux/features/rankSlice';

const Home: NextPage = () => {
  const tableData = useSelector((state: RootState) => state.playerRank)
  const {updateRanks} = usePinPong()
  const [refreshCounter, setRefreshCounter] = React.useState(0);

  React.useEffect(() => {
    fetchPlayerRanks()
  }, [])
  async function fetchPlayerRanks() {
    const {data}:any = await API.graphql({
      query: listPlayersByRank, variables: { 
        playerByRank:"Rank",
        sortDirection:"DESC"
       }
    })
    updateRanks(data.listPlayersByRank.items)
  }


  
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box >
      <TableContainer component={Paper}>
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell>GameId</TableCell>
            <TableCell >Player</TableCell>
            <TableCell >Wins</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
     
          {tableData && tableData.map((row:RankStat, i:number) =>
            <TableRow
              key={row.id}

            >
              <TableCell >
                {row.id}
              </TableCell>
              <TableCell >
              {row.name}
              </TableCell>
              <TableCell >
              {row.wins}
              </TableCell>
            </TableRow>
          )
          }
        </TableBody>
      </Table>
    </TableContainer>
    <PingPongModal/>
    </Box>
    </div>
  )
}

export default Home
